[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
	from="/computing/iPad/2020/10/31/ipados_review"
	to="/blog/ipados_review"

[[redirects]]
	from="/networking/2020/09/14/iot-vlan-edgeos"
	to="/blog/iot-vlan-edgeos"

[[redirects]]
	from="/networking/2020/05/01/nebula"
	to="/blog/nebula"

[[redirects]]
	from="/home_networking/2020/04/09/quick-tip-macos-as-a-cache-for-apple-devices"
	to="/blog/quick-tip-macos-as-a-cache-for-apple-devices"

[[redirects]]
	from="/networking/2020/04/05/pfSense_multiple_wan"
	to="/blog/pfSense_multiple_wan"

[[redirects]]
	from="/home-automation/2020/03/10/ansible_tasmota"
	to="/blog/ansible_tasmota"

[[redirects]]
	from="/finance/home-automation/2020/03/02/netflix-payments-home-assistant"
	to="/blog/netflix-payments-home-assistant"
