# theme.toml template for a Hugo theme
# Based on hugo-bearblog
# https://github.com/janraasch/hugo-bearblog/
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Eliseo Martelli theme"
license = "MIT"
licenselink = "https://github.com/janraasch/hugo-bearblog/blob/master/LICENSE"
description = "A bearblog inspired theme for eliseomartelli.it"
homepage = "https://github.com/eliseomartelli/eliseomartelli.it
tags = []
features = []
min_version = "v0.110.0"
# https://gohugo.io/content-management/taxonomies#default-taxonomies
# https://gohugo.io/templates/taxonomy-templates/#example-list-tags-in-a-single-page-template
# https://gohugo.io/templates/taxonomy-templates/#example-list-all-site-tags

# If porting an existing theme
[original]
  name = "ʕ•ᴥ•ʔ Bear Blog"
  homepage = "https://bearblog.dev"
  repo = "https://github.com/HermanMartinus/bearblog"
